version: '3.8'

services:
  db:
    image: postgres:13
    container_name: feedback_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: feedback_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  test_db:
    image: postgres:13
    container_name: feedback_app_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: feedback_app_test
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: backend/
    container_name: feedback_app_backend
    command: sh -c "./wait-for-db.sh db && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:root@db/feedback_app
      TEST_DATABASE_URL: postgresql+asyncpg://postgres:root@test_db/feedback_app_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    depends_on:
      - db
      - test_db
    restart: on-failure

  frontend:
    build: frontend/
    container_name: feedback_app_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    command: sh -c "npm install && npm run serve"

volumes:
  postgres_data:
  test_postgres_data: