"""Add comment field to feedback

Revision ID: 2f0dba82890f
Revises: b9acff6151e3
Create Date: 2024-07-06 05:12:14.501369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0dba82890f'
down_revision: Union[str, None] = 'b9acff6151e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'comment')
    # ### end Alembic commands ###
